// Generated by npm run i18n:generate. Edit locales instead.
import r0 from './locales/en-US/calendar.json';
import r1 from './locales/en-US/chat.json';
import r2 from './locales/en-US/common.json';
import r3 from './locales/en-US/errors.json';
import r4 from './locales/en-US/native.json';
import r5 from './locales/en-US/network.json';
import r6 from './locales/en-US/optical.json';
import r7 from './locales/en-US/projects.json';
import r8 from './locales/en-US/reports.json';
import r9 from './locales/en-US/settings.json';
import r10 from './locales/en-US/tasks.json';
import r11 from './locales/zh-CN/calendar.json';
import r12 from './locales/zh-CN/chat.json';
import r13 from './locales/zh-CN/common.json';
import r14 from './locales/zh-CN/errors.json';
import r15 from './locales/zh-CN/native.json';
import r16 from './locales/zh-CN/network.json';
import r17 from './locales/zh-CN/optical.json';
import r18 from './locales/zh-CN/projects.json';
import r19 from './locales/zh-CN/reports.json';
import r20 from './locales/zh-CN/settings.json';
import r21 from './locales/zh-CN/tasks.json';
export const resources = {"en-US": {"calendar": r0, "chat": r1, "common": r2, "errors": r3, "native": r4, "network": r5, "optical": r6, "projects": r7, "reports": r8, "settings": r9, "tasks": r10},
"zh-CN": {"calendar": r11, "chat": r12, "common": r13, "errors": r14, "native": r15, "network": r16, "optical": r17, "projects": r18, "reports": r19, "settings": r20, "tasks": r21}};
export const languageMetadata = [
  {
    "code": "en-US",
    "nativeName": "English",
    "aliases": [
      "en"
    ],
    "direction": "ltr"
  },
  {
    "code": "zh-CN",
    "nativeName": "简体中文",
    "aliases": [
      "zh"
    ],
    "direction": "ltr"
  }
] as const;
export const localeCodes = ["en-US","zh-CN"] as const;
